'use client';

import React, { useState, useEffect, Suspense } from 'react';
import { useSearchParams } from 'next/navigation';
import { FileSpreadsheet, Download, Sparkles, FileText, CheckCircle2 } from 'lucide-react';
import { Card } from '@/components/ui/Card';
import { Button } from '@/components/ui/Button';
import { Badge } from '@/components/ui/Badge';
import { api } from '@/lib/api';

function ReportsContent() {
  const searchParams = useSearchParams();
  const initialPaperId = searchParams.get('paperId');

  const [paperId, setPaperId] = useState<string | null>(initialPaperId);
  const [reportType, setReportType] = useState('RESEARCH_REPORT');
  const [format, setFormat] = useState('PDF');
  const [loading, setLoading] = useState(false);
  const [reportData, setReportData] = useState<any>({
    title: 'General Quantification of Covariate and Concept Shifts - Technical Report',
    content: `# Research2Reality AI Document Report
*Generated by Research2Reality AI Platform*

## Executive Summary
This document presents the complete technical synthesis, literature gap breakdown, empirical experiment metrics, executable PyTorch model code, and investor pitch deck strategy for General Quantification of Covariate and Concept Shifts.

## Benchmark Datasets & Algorithms
- Datasets: PACS, Novozymes, ColoredMNIST
- Algorithms: DataShifts Algorithm, Entropic Optimal Transport, Gamma-Star Concept Shift Metrics

## Key Performance Metrics
- Shift Detection Speedup: 3.2x vs Wasserstein Distance
- Latency (p99): 42ms
- VRAM Footprint: Sub-50ms matrix computation
`
  });

  const reportTypes = [
    { id: 'RESEARCH_REPORT', label: 'Research Report' },
    { id: 'LITERATURE_REVIEW', label: 'Literature Review' },
    { id: 'PROJECT_PROPOSAL', label: 'Project Proposal' },
    { id: 'INNOVATION', label: 'Innovation Report' },
    { id: 'PATENT', label: 'Patent Report' },
    { id: 'STARTUP', label: 'Startup Pitch Report' },
    { id: 'GRANT', label: 'Grant Proposal' },
  ];

  useEffect(() => {
    const activeId = paperId || (typeof window !== 'undefined' ? localStorage.getItem('r2r_active_paper_id') : null);
    if (activeId) {
      setPaperId(activeId);
      loadOrGenerateReport(activeId);
    }
  }, [paperId]);

  const loadOrGenerateReport = async (id: string) => {
    setLoading(true);
    try {
      // Step 1: Check DB for saved report
      const getRes = await api.getReport(id);
      if (getRes.success && getRes.data?.report) {
        setReportData(getRes.data.report);
      } else {
        // Step 2: Generate report using paperId
        const genRes = await api.generateReport({ paperId: id, type: reportType, format });
        const data = genRes.data as any;
        if (genRes.success && data?.report) {
          setReportData(data.report);
        }
      }
    } catch (err) {
      console.error('Report load error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleGenerate = async () => {
    setLoading(true);
    try {
      const res = await api.generateReport({ paperId: paperId || undefined, type: reportType, format });
      const data = res.data as any;
      if (res.success && data?.report) {
        setReportData(data.report);
      }
    } catch (err) {
      console.error('Report error:', err);
    } finally {
      setLoading(false);
    }
  };

  const handleDownload = () => {
    const blob = new Blob([reportData.content], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `Research2Reality_${reportType}_${format}.md`;
    a.click();
  };

  return (
    <div className="space-y-6 pb-12">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-2xl sm:text-3xl font-extrabold text-slate-900 dark:text-slate-100 flex items-center gap-2">
            <FileSpreadsheet className="w-7 h-7 text-emerald-500" />
            Publication-Ready Report Generator
          </h1>
          <p className="text-sm text-slate-500 dark:text-slate-400 mt-1">
            Generate and export PDF, DOCX, & PPT reports for research papers, grant proposals, and startup pitch decks.
          </p>
        </div>

        <Button variant="glow" onClick={handleDownload} leftIcon={<Download className="w-4 h-4" />}>
          Download {format} Document
        </Button>
      </div>

      <Card glass className="p-6 space-y-4">
        <label className="block text-xs font-bold uppercase tracking-wider text-slate-500 mb-2">Select Report Format & Type</label>
        <div className="flex flex-wrap gap-2">
          {reportTypes.map((t) => (
            <button
              key={t.id}
              onClick={() => setReportType(t.id)}
              className={`px-3 py-1.5 text-xs rounded-xl font-medium transition-all ${
                reportType === t.id
                  ? 'bg-brand-600 text-white font-bold shadow-sm'
                  : 'bg-slate-100 dark:bg-slate-800 text-slate-600 dark:text-slate-400'
              }`}
            >
              {t.label}
            </button>
          ))}
        </div>

        <div className="flex items-center gap-4 pt-2">
          <span className="text-xs font-bold text-slate-400 uppercase">Target Export Format:</span>
          {['PDF', 'DOCX', 'PPT'].map((f) => (
            <label key={f} className="flex items-center gap-1.5 text-xs text-slate-300 cursor-pointer">
              <input type="radio" name="format" checked={format === f} onChange={() => setFormat(f)} />
              <span>{f}</span>
            </label>
          ))}

          <Button variant="primary" size="sm" className="ml-auto" onClick={handleGenerate} isLoading={loading} leftIcon={<Sparkles className="w-4 h-4" />}>
            Generate Report
          </Button>
        </div>
      </Card>

      <Card glass className="p-8 space-y-4">
        <div className="flex items-center justify-between pb-4 border-b border-slate-200 dark:border-darkBorder">
          <Badge variant="brand">{reportType.replace('_', ' ')}</Badge>
          <span className="text-xs text-slate-400">Export Ready: {format}</span>
        </div>

        <pre className="p-6 rounded-2xl bg-slate-900 text-slate-100 text-xs font-mono overflow-x-auto leading-relaxed border border-slate-800">
          {reportData.content}
        </pre>
      </Card>
    </div>
  );
}

export default function ReportsPage() {
  return (
    <Suspense fallback={<div className="p-8 text-center text-slate-400">Loading Report Generator...</div>}>
      <ReportsContent />
    </Suspense>
  );
}
